# Generated by Django 2.2.3 on 2019-07-16 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('hash', models.UUIDField(default=rooms.models._generate_hash, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_posted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Chatroom')),
            ],
        ),
    ]
