# Generated by Django 2.2.3 on 2019-07-16 18:58

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='hash',
            field=models.CharField(default=rooms.models._generate_hash, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
